# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorlBorder',
            new_name='WorldBorder',
        ),
    ]
